import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Load the fonts with variables for CSS custom properties
const geistSans = Geist({
  variable: "--font-geist-sans",  // Custom CSS variable for Geist font
  subsets: ["latin"],  // Specify which subsets of the font to include
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",  // Custom CSS variable for Geist Mono font
  subsets: ["latin"],  // Specify which subsets of the font to include
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Add metadata or any other head tags here */}
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
